### ISSUE TITLE
EISDIR illegal operation error

### ISSUE THREAD

**Issue by spicydonuts** [franciscop/legally#1]
```
/project/dir » ianal
fs.js:651
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:651:19)
    at Object.fs.readFileSync (fs.js:472:24)
    at open (/Users/trotter/.nvm/versions/node/v5.3.0/lib/node_modules/ianal/index.js:24:59)
    at /Users/trotter/.nvm/versions/node/v5.3.0/lib/node_modules/ianal/index.js:73:14
    at Array.reduce (native)
    at Object.<anonymous> (/Users/trotter/.nvm/versions/node/v5.3.0/lib/node_modules/ianal/index.js:43:55)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
```

os x 10.11.2, node 5.3.0 (via nvm), ianal 1.0.0

**Comment by franciscop** [comment]
This seems to be the error, should be easy to fix:

> http://stackoverflow.com/q/25883775/938236

**Comment by EvanHahn** [comment]
Getting the same error on Node 4.3.1 on Linux.

**Comment by franciscop** [comment]
I changed the whole file reading function so it will probably work or give a different error.

Note: the library was renamed to `legally`

**Comment by franciscop** [comment]
Also note, the library is for Node 6.0.0+, which has been specified now in 2.8.0's package.json
