### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by kmerhi** [franciscop/legally#13]
After installing `legally` globally and running it from the root of my project, I get the following output:
```
> legally
~/.nvm/versions/node/v5.11.1/lib/node_modules/legally/lib/license.js:6
module.exports = function(text, def = []){
                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kmerhi/.nvm/versions/node/v5.11.1/lib/node_modules/legally/lib/legally.js:2:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by kmerhi** [comment]
Nevermind, the issue went away after I updated my node and npm.  Cheers - K

**Comment by franciscop** [comment]
Yes, it is using ES6 so you'd need a modern Node.js version. Glad you could make it work.
