### ISSUE TITLE
legally -l -r 'cannot find module'

### ISSUE THREAD

**Issue by jandockx** [franciscop/legally#17]
Install was done with `yarn`.

The relevant direct dependency is

````
  "devDependencies": {
    …
    "@ppwcode/terraform-ppwcode-modules": "^3.8.0",
    …
    "legally": "^2.10.0",
    …
  }
````

`@ppwcode/terraform-ppwcode-modules` has relevant dependencies

````
  "dependencies": {
    "@ppwcode/node-gitinfo": "^2.2.0",
    "@toryt/contracts-ii": "^1.2.0",
    …
  }
````
`@ppwcode/node-gitinfo` has relevant dependencies

````
  "dependencies": {
    "@toryt/contracts-ii": "^2.1.3",
    …
  },
````

Executing

````
>yarn run legally -l -r
````

results in

````
yarn run v1.3.2
$ /<PWD>/node_modules/.bin/legally -l -r
module.js:540
    throw err;
    ^

Error: Cannot find module '/<PWD>/node_modules/@ppwcode/node-gitinfo/node_modules/@toryt/package.json'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at getPackage (/<PWD>/node_modules/legally/lib/legally.js:17:13)
    at packages.reduce (/<PWD>/node_modules/legally/lib/legally.js:36:8)
    at Array.reduce (<anonymous>)
    at module.exports.root (/<PWD>/node_modules/legally/lib/legally.js:34:19)
    at Object.<anonymous> (/<PWD>/node_modules/legally/index.js:50:14)
    at Module._compile (module.js:643:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

The problem seems to be that the `package.json` file `legally` is looking for is at 

````
/<PWD>/node_modules/@ppwcode/node-gitinfo/node_modules/@toryt/contracts-ii/package.json
````

1 level down.

I assume this is a case not correctly covered by the patch for dealing with scoped packages?

**Comment by franciscop** [comment]
Scoped packages inside scoped packages, interesting issue. Thank you fir debugging it, that information and traces are very useful. Please feel free to do a PR, while I agree it is an issue it is low priority for me right now.

**Comment by frbar** [comment]
Hi,

same issue here. 

```
Error: Cannot find module '<xxx>/node_modules/resolve-pathname/package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```
`legally` looks promising!

**Comment by EyMaddis** [comment]
Also breaks with `@babel/*` package since version 7 because they switched to scoping.

**Comment by franciscop** [comment]
These issues seem to have been fixed since the latest code rewrite to use `fs-array` with `walk()` internally. Please feel free to open a new issue if this is not the case.
