### ISSUE TITLE
Does legally work on Windows with node 8 and npm 5.6

### ISSUE THREAD

**Issue by sfali16** [franciscop/legally#18]
Is legally supported on windows using node v8.9.4 and npm 5.6.0 ?
I tried to run `legally` by installing globally using `npm install legally -g` 
Then ran on the command line as follows:
`> legally node_modules`

This failed with the following error:

> C:\dev\git\vendor-driver-library>legally node_modules
> Working on it. It will take a while...
> npm ERR! Parameter "url" must be a string, not undefined
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\sali\AppData\Roaming\npm-cache\_logs\2018-03-16T16_38_20_964Z-debug.log
> child_process.js:644
>     throw err;
>     ^
> 
> Error: Command failed: cd "C:\dev\git\vendor-driver-library/.tmp/legally" && npm init --yes && npm install node_modules --save --ignore-scripts
> npm ERR! Parameter "url" must be a string, not undefined
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\sali\AppData\Roaming\npm-cache\_logs\2018-03-16T16_38_20_964Z-debug.log
> 
>     at checkExecSyncError (child_process.js:601:13)
>     at Object.execSync (child_process.js:641:13)
>     at exec (C:\dev\nodejs\node_modules\legally\lib\remote.js:2:48)
>     at module.exports (C:\dev\nodejs\node_modules\legally\lib\remote.js:36:13)
>     at Object.<anonymous> (C:\dev\nodejs\node_modules\legally\index.js:42:3)
>     at Module._compile (module.js:643:30)
>     at Object.Module._extensions..js (module.js:654:10)
>     at Module.load (module.js:556:32)
>     at tryModuleLoad (module.js:499:12)
>     at Function.Module._load (module.js:491:3)

**Comment by sfali16** [comment]
FWIW i had tried running `legally` without any arguments first and that led me to another error, so I thought I was using it wrong and therefore tried `legally node_modules`

```C:\dev\git\vendor-driver-library>legally
fs.js:675
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at open (C:\dev\nodejs\node_modules\legally\lib\open.js:10:64)
    at file.find.name (C:\dev\nodejs\node_modules\legally\lib\open.js:7:42)
    at Array.find (native)
    at open (C:\dev\nodejs\node_modules\legally\lib\open.js:7:29)
    at packages.reduce (C:\dev\nodejs\node_modules\legally\lib\legally.js:39:35)
    at Array.reduce (<anonymous>)
    at module.exports.root (C:\dev\nodejs\node_modules\legally\lib\legally.js:34:19)
```

**Comment by franciscop** [comment]
Hi @sfali16, thanks for reporting it. I tried it once on windows and it worked, but beyond that I do not offer windows support on most of my packages. The syntax should be just `legally` and never `legally node_modules`. Does either of those work for you?

```bash
npx legally
npx legally .
```

**Comment by sfali16** [comment]
Tried the above two commeands that also didn't work. 
```
sali@ATH021528 MINGW64 /c/dev/temp/vendor-driver-library (master)
$ npx legally
npx: installed 1 in 2.32s
Path must be a string. Received undefined
C:\dev\nodejs\node_modules\legally\index.js
EISDIR: illegal operation on a directory, read

sali@ATH021528 MINGW64 /c/dev/temp/vendor-driver-library (master)
$ npx legally .
npx: installed 1 in 1.876s
Path must be a string. Received undefined
C:\dev\nodejs\node_modules\legally\index.js
Working on it. It will take a while...
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN legally@1.0.0 No description
npm WARN legally@1.0.0 No repository field.

No modules installed. Are you in the right directory?
```
It's almost like it is not operating on the correct parameters.  I noticed that there is some windows-specific argument handling performed in index.js perhaps to workaround a minimist bug. Let me take a look at the `legally` source and see if i can figure it out.

**Comment by sfali16** [comment]
Hi @franciscop 
I did some debugging and figured out that it was actually a particular npm package called `sjcl` that doesn't provide a README, license or package.json entry for license. The absence of all of the above causes the `EISDIR` exception in `legally`. In `open.js`, this leads to passinig a directory to `readFileSync`. This exception crashes the legally program. 
I created a package.json that you can drop into an empty folder and run `npm install` to see the issue for yourself.

On my system, as a workaround, I surrounded the readFileSync call with a try-catch in open.js and the rest of my packages in my real app processed just fine.  
Would you accept a PR with the try-catch ?  Would that highlight a package as "Unable to determine license" but not fail the entire inspection? Or is there a better way?

**Comment by sfali16** [comment]
The package.json couldn't be attached so pasting the code here:
```
{
  "name": "use-sjcl",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "sjcl": "^1.0.7"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Faraz Ali",
  "license": "MIT"
}
```

**Comment by franciscop** [comment]
Ah thanks a lot! That sounds about right.

I think a better alternative would be to avoid calling `readFileSync` in the first place. It could also use a bit of clean-up. Something like this might work:

```js
// Don't even attempt since there's no valid file
if (!mod || !file) return;
var path = mod + '/' + file;
// Does not exist in the filepath
if (!fs.existsSync(path)) return;
return req ? require(path) : fs.readFileSync(path, 'utf8');
```

It is asking a lot, but would you mind testing this please? Then feel free to do a PR :smiley:

**Comment by sfali16** [comment]
Hi, I haven't had a chance to do this, but I plan on trying this out and then making a PR. Look for it in the next two-three weeks.
