### ISSUE TITLE
Legally latest on Windows w/ Node 8.12, NPM 6.4.1: error

### ISSUE THREAD

**Issue by jessejacob** [franciscop/legally#21]
Legally is installed globally and I'm attempting to run it from a directory with a node_modules directory inside of it. but it seems to bomb in any project I try it on:
```
C:\workspace\project>legally
Error: No modules found. Are you in the right directory?
    at module.exports (C:\Users\jesse\AppData\Roaming\npm\node_modules\legally\src\analysis.js:14:11)
    at C:\Users\jesse\AppData\Roaming\npm\node_modules\legally\cli.js:25:11
    at <anonymous>
(node:33544) UnhandledPromiseRejectionWarning: Error: No modules found. Are you in the right directory?
    at module.exports (C:\Users\jesse\AppData\Roaming\npm\node_modules\legally\src\analysis.js:14:11)
    at C:\Users\jesse\AppData\Roaming\npm\node_modules\legally\cli.js:25:11
    at <anonymous>
(node:33544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Any ideas?

**Comment by franciscop** [comment]
Hi, Windows should not be working previously but with the just published `legally@3.3.6` it should be working again! I added AppVeyor for automated tests as well.

Please let me know if this issue persists.
